apiVersion: v1
kind: Pod
metadata:
  name: dapoapplication
  labels:
    app: frontend
spec:
  containers:
    - name: dapoapplication
      image: nginx
      ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dapoapplication
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: dapoapplication
          image: nginx
          ports:
            - containerPort: 8080
    