apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-user
  namespace: daas

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: daas
  name: nginx-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-role-binding
  namespace: daas
subjects:
- kind: ServiceAccount
  name: nginx-user
  namespace: daas
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io


# Validate service account can access pods
# kubectl auth can-i get pods --as=system:serviceaccount:daas:nginx-user
